/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MINIFYJPEG_H_RPCGEN
#define _MINIFYJPEG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct minify_in {
	struct {
		u_int high_res_img_len;
		char *high_res_img_val;
	} high_res_img;
};
typedef struct minify_in minify_in;

struct minify_out {
	struct {
		u_int low_res_img_len;
		char *low_res_img_val;
	} low_res_img;
};
typedef struct minify_out minify_out;

struct minifyjpeg_res {
	int errno;
	union {
		minify_out res_img;
	} minifyjpeg_res_u;
};
typedef struct minifyjpeg_res minifyjpeg_res;

#define MINIFYJPEG_PROG 0x31230000
#define MINIFYJPEG_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define MINIFYJPEG_PROC 1
extern  minifyjpeg_res * minifyjpeg_proc_1(minify_in *, CLIENT *);
extern  minifyjpeg_res * minifyjpeg_proc_1_svc(minify_in *, struct svc_req *);
extern int minifyjpeg_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MINIFYJPEG_PROC 1
extern  minifyjpeg_res * minifyjpeg_proc_1();
extern  minifyjpeg_res * minifyjpeg_proc_1_svc();
extern int minifyjpeg_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_minify_in (XDR *, minify_in*);
extern  bool_t xdr_minify_out (XDR *, minify_out*);
extern  bool_t xdr_minifyjpeg_res (XDR *, minifyjpeg_res*);

#else /* K&R C */
extern bool_t xdr_minify_in ();
extern bool_t xdr_minify_out ();
extern bool_t xdr_minifyjpeg_res ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MINIFYJPEG_H_RPCGEN */
