/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "minifyjpeg.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

minifyjpeg_res *
minifyjpeg_proc_1(minify_in *argp, CLIENT *clnt)
{
	static minifyjpeg_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, MINIFYJPEG_PROC,
		(xdrproc_t) xdr_minify_in, (caddr_t) argp,
		(xdrproc_t) xdr_minifyjpeg_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
