/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "minifyjpeg.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

pthread_t p_thread;
pthread_attr_t attr;
int uncopied_args = 0;
pthread_mutex_t args_mutex;
pthread_cond_t args_cv;

typedef struct worker_arg
{
	struct svc_req *rqstp;
	SVCXPRT *transp;
} worker_arg;

int
_minifyjpeg_proc_1 (minify_in  *argp, void *result, struct svc_req *rqstp)
{
	return (minifyjpeg_proc_1_svc(*argp, result, rqstp));
}

void* worker_func(void *arg) {
	pthread_mutex_lock(&args_mutex);

	union {
		minify_in minifyjpeg_proc_1_arg;
	} argument;
	union {
		minify_out minifyjpeg_proc_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);
	worker_arg* req_arg;

	req_arg = (worker_arg*)arg;

	struct svc_req *rqstp = req_arg-> rqstp;
	register SVCXPRT *transp = req_arg-> transp;

	switch (rqstp->rq_proc) {
		case NULLPROC:
			(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
			return NULL;

		case MINIFYJPEG_PROC:
			_xdr_argument = (xdrproc_t) xdr_minify_in;
			_xdr_result = (xdrproc_t) xdr_minify_out;
			local = (bool_t (*) (char *, void *,  struct svc_req *))_minifyjpeg_proc_1;
			break;

		default:
			svcerr_noproc (transp);
			return NULL;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return NULL;
	}
  uncopied_args--;
	pthread_mutex_unlock(&args_mutex);
	pthread_cond_signal(&args_cv);

	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
  printf("reply");
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!minifyjpeg_prog_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return NULL;
}

static void
minifyjpeg_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	pthread_mutex_lock(&args_mutex);

	worker_arg* arg;

	arg	= (worker_arg*)malloc(sizeof(worker_arg));
	arg->rqstp = rqstp;
	arg->transp = transp;

	pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_DETACHED);
	pthread_create(&p_thread, &attr, worker_func, (void *)arg);
	uncopied_args++;

	while(uncopied_args > 0) {
		pthread_cond_wait(&args_cv, &args_mutex);
	}
	pthread_mutex_unlock(&args_mutex);
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pthread_mutex_init(&args_mutex, NULL);
	pthread_cond_init (&args_cv, NULL);

	pmap_unset (MINIFYJPEG_PROG, MINIFYJPEG_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, MINIFYJPEG_PROG, MINIFYJPEG_VERS, minifyjpeg_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (MINIFYJPEG_PROG, MINIFYJPEG_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, MINIFYJPEG_PROG, MINIFYJPEG_VERS, minifyjpeg_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (MINIFYJPEG_PROG, MINIFYJPEG_VERS, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
